name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  go:
    uses: jacaudi/github-actions/.github/workflows/lint.yml@v0.11.1
    with:
      go: true
      working-directory: server

  config:
    uses: jacaudi/github-actions/.github/workflows/lint.yml@v0.11.1
    with:
      yaml: true
      yamllint-config: .yamllint.yml
      json: true
